<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class MissionTemplateSeeder extends Seeder
{
    public function run()
    {
        $now = Time::now()->toDateTimeString();

        $missions = [
            // --- PALIERS DE DÉBUTANT (Niveaux 1 à 3) ---
            [
                'title'             => 'Patrouille de routine',
                'description'       => 'Effectuez un balayage de sécurité autour du spatioport pour dissuader les voleurs de seconde zone.',
                'level_required'    => 1,
                'power_required'    => 50,
                'stamina_cost'      => 5,
                'team_size_max'     => 1,
                'credits_reward'    => 100,
                'energy_reward'     => 10,
                'experience_reward' => 40,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Nettoyage de vermine orbitale',
                'description'       => 'Eliminez les drones sauvages qui parasitent les antennes de communication du secteur.',
                'level_required'    => 1,
                'power_required'    => 100,
                'stamina_cost'      => 6,
                'team_size_max'     => 1,
                'credits_reward'    => 150,
                'energy_reward'     => 15,
                'experience_reward' => 60,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Livraison de conteneurs scellés',
                'description'       => 'Transportez un lot de composants industriels vers l\'avant-poste le plus proche sans poser de questions.',
                'level_required'    => 2,
                'power_required'    => 200,
                'stamina_cost'      => 8,
                'team_size_max'     => 2,
                'credits_reward'    => 250,
                'energy_reward'     => 20,
                'experience_reward' => 90,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Sécurisation de la raffinerie',
                'description'       => 'Protéger le complexe d\'extraction de plasma contre une escouade d\'écorcheurs locaux.',
                'level_required'    => 2,
                'power_required'    => 350,
                'stamina_cost'      => 10,
                'team_size_max'     => 2,
                'credits_reward'    => 380,
                'energy_reward'     => 30,
                'experience_reward' => 130,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Escorte d\'un convoi médical',
                'description'       => 'Assurez la sécurité d\'un vaisseau de secours traversant une zone d\'astéroïdes instable.',
                'level_required'    => 3,
                'power_required'    => 500,
                'stamina_cost'      => 12,
                'team_size_max'     => 3,
                'credits_reward'    => 500,
                'energy_reward'     => 45,
                'experience_reward' => 180,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // --- PALIERS INTERMÉDIAIRES (Niveaux 4 à 7) ---
            [
                'title'             => 'Raid sur l\'avant-poste pirate',
                'description'       => 'Infiltrez une station clandestine pour récupérer les registres de vol volés.',
                'level_required'    => 4,
                'power_required'    => 750,
                'stamina_cost'      => 14,
                'team_size_max'     => 3,
                'credits_reward'    => 700,
                'energy_reward'     => 60,
                'experience_reward' => 240,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Extraction de fluide kaosmïk',
                'description'       => 'Récoltez des échantillons énergétiques à la surface d\'une comète sous de fortes radiations.',
                'level_required'    => 4,
                'power_required'    => 1000,
                'stamina_cost'      => 15,
                'team_size_max'     => 3,
                'credits_reward'    => 850,
                'energy_reward'     => 90,
                'experience_reward' => 300,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Interception du destroyer noir',
                'description'       => 'Neutralisez le réacteur principal d\'un croiseur ennemi avant qu\'il n\'atteigne l\'orbite haute.',
                'level_required'    => 5,
                'power_required'    => 1300,
                'stamina_cost'      => 18,
                'team_size_max'     => 4,
                'credits_reward'    => 1100,
                'energy_reward'     => 120,
                'experience_reward' => 380,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Siphon de données quantiques',
                'description'       => 'Piratez le relais de transmission militaire du secteur 7 sans déclencher l\'alarme générale.',
                'level_required'    => 6,
                'power_required'    => 1700,
                'stamina_cost'      => 20,
                'team_size_max'     => 4,
                'credits_reward'    => 1400,
                'energy_reward'     => 150,
                'experience_reward' => 460,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Protection du sénateur en transit',
                'description'       => 'Repoussez une série de navettes d\'assassins ciblant le cortège diplomatique.',
                'level_required'    => 7,
                'power_required'    => 2200,
                'stamina_cost'      => 22,
                'team_size_max'     => 4,
                'credits_reward'    => 1800,
                'energy_reward'     => 180,
                'experience_reward' => 550,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // --- PALIERS AVANCÉS (Niveaux 8 à 12) ---
            [
                'title'             => 'Pillage d\'une épave ancienne',
                'description'       => 'Explorez un cuirassé abandonné dérivant aux confins du vide pour mettre la main sur des modules rares.',
                'level_required'    => 8,
                'power_required'    => 2800,
                'stamina_cost'      => 25,
                'team_size_max'     => 5,
                'credits_reward'    => 2300,
                'energy_reward'     => 220,
                'experience_reward' => 650,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Sabotage du réseau sub-spatial',
                'description'       => 'Infiltrez une station d\'écoute et déposez des charges explosives sur le générateur d\'ondes.',
                'level_required'    => 9,
                'power_required'    => 3500,
                'stamina_cost'      => 28,
                'team_size_max'     => 5,
                'credits_reward'    => 2900,
                'energy_reward'     => 270,
                'experience_reward' => 780,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Chasse au prime : Varek le Borgne',
                'description'       => 'Traquez et capturez un commandant mercenaire recherché par plusieurs factions syndicales.',
                'level_required'    => 10,
                'power_required'    => 4300,
                'stamina_cost'      => 30,
                'team_size_max'     => 5,
                'credits_reward'    => 3600,
                'energy_reward'     => 330,
                'experience_reward' => 920,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Nettoyage du secteur dévasté',
                'description'       => 'Affrontez une horde de drones de défense devenus autonomes et hostiles après un dysfonctionnement.',
                'level_required'    => 11,
                'power_required'    => 5200,
                'stamina_cost'      => 32,
                'team_size_max'     => 5,
                'credits_reward'    => 4400,
                'energy_reward'     => 400,
                'experience_reward' => 1100,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Reconquête de la station Alpha',
                'description'       => 'Reprenez le contrôle d\'un centre de recherche stratégique envahi par des rebelles armés.',
                'level_required'    => 12,
                'power_required'    => 6200,
                'stamina_cost'      => 35,
                'team_size_max'     => 5,
                'credits_reward'    => 5300,
                'energy_reward'     => 480,
                'experience_reward' => 1300,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // --- PALIERS ÉPIQUES & EXPERTS (Niveaux 13 à 20) ---
            [
                'title'             => 'Conflit dans la nébuleuse de feu',
                'description'       => 'Prenez part à une bataille navale majeure au milieu de tempêtes ioniques détruisant les boucliers.',
                'level_required'    => 13,
                'power_required'    => 7500,
                'stamina_cost'      => 38,
                'team_size_max'     => 5,
                'credits_reward'    => 6500,
                'energy_reward'     => 570,
                'experience_reward' => 1550,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Infiltration du nid d\'acier',
                'description'       => 'Déposez une escouade au cœur d\'une Forteresse Stellaire pour désactiver son canon orbital.',
                'level_required'    => 15,
                'power_required'    => 9500,
                'stamina_cost'      => 40,
                'team_size_max'     => 5,
                'credits_reward'    => 8000,
                'energy_reward'     => 700,
                'experience_reward' => 1900,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Assaut sur la Citadelle Kaosmïk',
                'description'       => 'Affrontez la garde d\'élite et neutralisez le haut commandant de l\'empire adverse.',
                'level_required'    => 17,
                'power_required'    => 12000,
                'stamina_cost'      => 45,
                'team_size_max'     => 5,
                'credits_reward'    => 10500,
                'energy_reward'     => 900,
                'experience_reward' => 2400,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Incursion dans l\'anomalie instable',
                'description'       => 'Pénétrez dans une faille spatio-temporelle pour extraire l\'énergie pure d\'une étoile mourante.',
                'level_required'    => 19,
                'power_required'    => 15000,
                'stamina_cost'      => 50,
                'team_size_max'     => 5,
                'credits_reward'    => 14000,
                'energy_reward'     => 1200,
                'experience_reward' => 3000,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'title'             => 'Annihilation du Léviathan d\'acier',
                'description'       => 'Missions Ultime : Abattez le vaisseau-monde géant qui menace de pulvériser le secteur entier.',
                'level_required'    => 20,
                'power_required'    => 20000,
                'stamina_cost'      => 60,
                'team_size_max'     => 5,
                'credits_reward'    => 20000,
                'energy_reward'     => 1800,
                'experience_reward' => 4200,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ];

        // Insertion massive
        $this->db->table('mission_templates')->insertBatch($missions);
    }
}